---
          - name: add key
            apt_key:
                    url: "https://repos.influxdata.com/influxdb.key"
                    state: present
            when: ansible_distribution == "Ubuntu"
          - name: add repo
            ansible.builtin.apt_repository:
                    repo: deb https://repos.influxdata.com/ubuntu focal stable
                    state: present
            when: ansible_distribution == "Ubuntu"
          - name: apt update
            apt:
                    update_cache: yes
            when: ansible_distribution == "Ubuntu"
          - name: install influxdb
            apt:
                    name: ['influxdb','python3-influxdb']
                    state: latest
            when: ansible_distribution == "Ubuntu"
          - name: allow port
            ufw:
                    rule: allow
                    port: 8086
                    proto: tcp
            when: ansible_distribution == "Ubuntu"
          - name: configure influxdb
            ini_file:
                    path: /etc/influxdb/influxdb.conf
                    section: http
                    option: "{{item}}"
                    value: 'true'
            with_items:
                    - enable
                    - log_enabled
                    - flux-enabled
          - name: configure influxdb port
            ini_file:
                    path: /etc/influxdb/influxdb.conf
                    section: http
                    option: "bind-address"
                    value: "':8086'"
          - name: restart influxdb
            service:
                    name: 'influxdb'
                    state: restarted
          - name: create_db
            influxdb_database:
                    hostname: "{{ip_database}}"
                    database_name: "{{databasename}}"
                    state: 'present'
          - name: create_user_db
            influxdb_user:
                    hostname: "{{ip_database}}"
                    user_name: "{{username}}"
                    user_password: "{{userpass}}"
                    state: 'present'
                    grants:
                            - database: "{{databasename}}"
                              privilege: 'all'

