---
          - name: add key
            apt_key:
                    url: "https://repos.influxdata.com/influxdb.key"
                    state: present
            when: ansible_distribution == "Ubuntu"
          - name: add repo
            ansible.builtin.apt_repository:
                    repo: deb https://repos.influxdata.com/ubuntu focal stable
                    state: present
            when: ansible_distribution == "Ubuntu"
          - name: apt update
            apt:
                    update_cache: yes
            when: ansible_distribution == "Ubuntu"
          - name: install influxdb
            apt:
                    name: ['influxdb','python3-influxdb']
                    state: latest
            when: ansible_distribution == "Ubuntu"
          - name: allow port
            ufw:
                    rule: allow
                    port: 8086
                    proto: tcp
            when: ansible_distribution == "Ubuntu"
         - name: remove file configure
            file:
                    path: /etc/influxdb/influxdb.conf
                    state: absent
          - name: Copy influxdb.conf file
            template:
                    src: template.j2
                    dest: /etc/influxdb/influxdb.conf
            notify:
                    - restart influxdb
