---
- hosts: ubuntu01
  tasks:
          - name: add repo
            get_url:
                    url: 'https://repos.influxdata.com/influxdb.key'
                    dest: /tmp/influxdb.key
          - name: add key
            ansible.builtin.apt_key:
                    file: /tmp/influxdb.key
                    state: present

          - name: source /lsb-release
            shell: source /root/.bashrc && source /etc/lsb-release
            args:
                    executable: /bin/bash
          - name: import repo
            shell: "echo 'deb https://repos.influxdata.com/ubuntu focal stable' > /etc/apt/sources.list.d/influxdb.list"
          - name: apt update
            apt:
                    update_cache: yes
          - name: install influxdb
            apt:
                    name: 'influxdb'
                    state: latest
          - name: start influxdb
            service:
                    name: 'influxdb'
                    state: started
          - name: allow port 8086
            ufw:
                    rule: allow
                    port: 8086
                    proto: tcp

          - name: allow port 8088
            ufw:
                    rule: allow
                    port: 8088
                    proto: tcp
          - name: cofigure influxdb
            ini_file:
                    path: /etc/influxdb/influxdb.conf
                    section: http
                    option: "{{item}}"
                    value: 'true'
            with_items:
                    - enable
                    - log_enabled
                    - flux-enabled

          - name: configure influxdb port
            ini_file:
                    path: /etc/influxdb/influxdb.conf
                    section: http
                    option: "bind-address"
                    value: "':8086'"
          - name: install python3-influxdb
            apt:
                    name: 'python3-influxdb'
                    state: latest
          - name: create_db
            influxdb_database:
                    hostname: 127.0.0.1
                    database_name: 'telegraf'
                    state: 'present'
          - name: create_user_db
            influxdb_user:
                    hostname: 127.0.0.1
                    user_name: 'telegraf'
                    user_password: 'telegraf'
                    state: 'present'
                    grants:
                            - database: 'telegraf'
                              privilege: 'all'
