---
- hosts: ubuntu02
  tasks:
          - name: add repo
            get_url:
                    url: 'https://repos.influxdata.com/influxdb.key'
                    dest: /tmp/influxdb.key
          - name: add key
            ansible.builtin.apt_key:
                    file: /tmp/influxdb.key
                    state: present

          - name: source /lsb-release
            shell: source /root/.bashrc && source /etc/lsb-release
            args:
                    executable: /bin/bash
          - name: import repo
            shell: "echo 'deb https://repos.influxdata.com/ubuntu focal stable' > /etc/apt/sources.list.d/influxdb.list"
          - name: apt update
            apt:
                    update_cache: yes
          - name: install influxdb-client
            apt:
                    name: 'influxdb-client'
                    state: latest
          - name: download telegraf
            get_url:
                    url: https://dl.influxdata.com/telegraf/releases/telegraf_1.21.4-1_amd64.deb
                    dest: /tmp/telegraf.deb
          - name: install telegraf
            apt:
                    deb: /tmp/telegraf.deb
          - name: start telegraf
            service:
                    name: 'telegraf'
                    state: started
          - name: configure telegraf
            ini_file:
                    path: /etc/telegraf/telegraf.conf
                    section: '[outputs.influxdb]'
                    option: "{{item}}"
                    value: "'telegraf'"
            with_items:
                    - database
                    - username
                    - password

          - name: configure influxdb port
            ini_file:
                    path: /etc/telegraf/telegraf.conf
                    section: '[outputs.influxdb]'
                    option: "urls"
                    value: "['http://10.0.0.52:8086']"
          - name: configure influxdb hostname
            ini_file:
                    path: /etc/telegraf/telegraf.conf
                    section: 'agent'
                    option: "hostname"
                    value: "'$HOSTNAME'"
          - name: restart telegraf
            service:
                    name: 'telegraf'
                    state: restarted
