# handlers file for telegraf
          - name: restart telegraf
            service:
                    name: 'telegraf'
                    state: restarted
          - name: start telegraf
            service:
                    name: 'telegraf'
                    state: started
